Improve authentication method support
cooncesean/mixpanel-query-py pull request #30
Opened 2017-04-01 23:42 UTC by thesmallestduck

why
---
Mixpanel documentation clearly states signature-based authentication is considered deprecated. However, on several occasions we have been informed there are no plans to discontinue support of signature-based authentication. There has been some interest in supporting the new "secret in header" means of authentication. Two PRs have been submitted to that effect:

https://github.com/cooncesean/mixpanel-query-py/pull/27
https://github.com/cooncesean/mixpanel-query-py/pull/29

In the interest of keeping this repo up to date, we should strive to conform to the latest documentation from Mixpanel.

what
---
this PR:

* creates a new `mixpanel_query.auth` module with two classes, `SignatureAuth` and `SecretAuth`
* adjusts `mixpanel_query.client.MixpanelQueryClient` to accept an auth_class upon initialization. This auth class is used to create an instance upon initialization for future use in authorizing requests
* adjusts `mixpanel_query.connection.Connection` to use the client's auth instance to authenticate requests
* moves the `unicode_urlencode` method from the connection class to `mixpanel_query.utils` so both authentication classes could use it

new usage
---
If we merge this PR and update the pip version, you should not have to make any changes to your code in a production environment what-so-ever. The same signature method of authentication will be used, any unit tests you have setup to introspect url parameters should see everything behaving as usual.

However, if you wish to switch production code to use the secret-based means of authentication, you should be able to do so like this:

BEFORE:
```
from mixpanel_query.client import MixpanelQueryClient

signature_client = MixpanelQueryClient(API_KEY, API_SECRET)
```

AFTER:
```
rom mixpanel_query.client import MixpanelQueryClient
from mixpanel_query.auth import SecretAuth

secret_client = MixpanelQueryClient(API_KEY, API_SECRET, auth_class=SecretAuth)
```

notes
---
* in the future, we can consider changing the default `auth_class` used by the client to be `SecretAuth`. We should most certainly do so if Mixpanel ever communicates their intent to discontinue support of the signature-based authentication method.
* thank you @drathm and @robin900 for your prior PRs on this (I leaned heavily on your PRs for the `SecretAuth` class.
* I have tested both authentication methods using the `get_segmentation` and `get_export` methods, and both are functioning well. I'd appreciate any additional tire-kicking folks can bring to the PR.

2017-04-01 23:56 UTC, frifri requested changes

2017-04-01 23:56 UTC, frifri commented on mixpanel_query/auth.py
> +import six
We could probably `isort` our imports

2017-04-01 23:56 UTC, frifri commented on mixpanel_query/auth.py
> +        for a in args:
Let's try to avoid one letter variables

2017-04-01 23:56 UTC, frifri commented on mixpanel_query/auth.py
> +            args_joined += _tobytes(a)
Can we not `format` the string and run `_tobytes` on it?
might be cleaner

2017-04-02 00:16 UTC, thesmallestduck commented on mixpanel_query/auth.py
> +import six
https://github.com/cooncesean/mixpanel-query-py/pull/30/commits/c2aae0cc44c6490f6041d129777d338699121dc4

2017-04-02 00:16 UTC, thesmallestduck commented on mixpanel_query/auth.py
> +        for a in args:
https://github.com/cooncesean/mixpanel-query-py/pull/30/commits/c2aae0cc44c6490f6041d129777d338699121dc4

2017-04-02 00:16 UTC, thesmallestduck commented on mixpanel_query/auth.py
> +            args_joined += _tobytes(a)
https://github.com/cooncesean/mixpanel-query-py/pull/30/commits/c2aae0cc44c6490f6041d129777d338699121dc4

2017-04-02 00:21 UTC, drathm commented
Great change! I've added JQL support to my local fork which requires the use of POST instead of the assumed GET in the connection class so I'll need to massage this a bit into my local branch.

I'm happy to submit another PR if desired. Here's my local branch with JQL
https://github.com/Resly/mixpanel-query-py/tree/add-jql

2017-04-02 00:30 UTC, frifri approved these changes

2017-04-02 00:41 UTC, thesmallestduck commented
@drathm it'd be great to support JQL, for sure. I'll take a look at your fork sometime this week. Otherwise PRs are always welcome.

2017-04-02 14:47 UTC, cooncesean commented on mixpanel_query/client.py
> +    def __init__(self, api_key, api_secret, auth_class=SignatureAuth, timeout=None):
If one of the goals of this PR is to _not_ affect existing users, we may want to add this new keyword arg to the last position in this `__init__` signature.

There _may_ be some users who are using positional args to invoke this method like so:

```python
mpqc = MixpanelQueryClient(key, secret, 600)
```

The call above "breaks" if the user upgrades.

2017-04-02 14:48 UTC, cooncesean commented on mixpanel_query/connection.py
> +        request_obj = self.client.auth.authenticate(url_without_params, params)
👍 much cleaner.

2017-04-02 14:50 UTC, cooncesean approved these changes
Light feedback around the `MixpanelQueryClient.__init__()` ... other than that, this looks great - thanks @thesmallestduck 👍

2017-04-03 02:17 UTC, thesmallestduck commented on mixpanel_query/client.py
> +    def __init__(self, api_key, api_secret, auth_class=SignatureAuth, timeout=None):
good point. https://github.com/cooncesean/mixpanel-query-py/pull/30/commits/4becc9e144baeb3a8d36ec72b32194a736ba111b

2017-04-03 16:54 UTC, cooncesean approved these changes
@thesmallestduck if you're happy with this, lets get it in and bump the version on pypi.

2017-04-03 16:59 UTC, merged